### ISSUE TITLE
Move .analyze-cache/ to $HOME and make it configurable

### ISSUE THREAD

**Issue by afiune** [chef/chef-analyze#101]
### Describe the Enhancement:

>As a chef-analyze user,
I would like the cache directory to be consistent and configurable,
So that I don't generate multiple directories on my workstation and also
So that I can configure a specific path to cache analyze data.

### Describe the Need:

If a user runs chef-analyze on multiple directories, we will be generating
multiple [`.analyze-cache/`](https://github.com/chef/chef-analyze/blob/master/pkg/reporting/cookbooks.go#L30-L31) directories on the local workstation. Instead,
we would like to be consistent and set the default cache directory to be
`$HOME/.analyze-cache/`

### Current Alternative

None. Remember where you have ran the command and move or delete
the cache data.

### Similar Issues
There is one issue to generate a `cleanup` command that might be a good
idea to [link](https://github.com/chef/chef-analyze/issues/80)

**Comment by afiune** [comment]
Could we leverage `$HOME/.chef-workstation` path?

**Comment by afiune** [comment]
Marked as critical since we do not want to release a version of chef-analyze that downloads
artifacts all over the users workstation.

**Comment by marcparadise** [comment]
I'm thinking we can do this as: 

~/.chef-workstation/reports/analyze
~/.chef-workstation/cache/analyze  

Already potentially in chef-workstatoin, if you use chef-run: 
~/.chef-workstation/logs
~/.chef-workstation/cache
~/.chef-workstation/telemetry
