### ISSUE TITLE
Remove .ruby-version and .rubocop.yml to prevent failures

### ISSUE THREAD

**Issue by tas50** [chef/chef-analyze#106]
## Description
Right now we have a lot of failures when a cookbook includes an outdated .ruby-version file or a .rubocop.yml file that includes legacy cop names. We need to remove these configs so that we can actually process these cookbooks.

Additionally, as time goes on users are going to start using the .rubocop.yml file to disable the Chef cops, which will mean chef-analyze will incorrectly return a cookbook as having no violations.

## Chef Analyze Version
master

## Platform Version
All

**Comment by tyler-ball** [comment]
https://github.com/chef/chef-analyze/pull/146 is less invasive than deleting an existing file and accomplishes our goal of ignoring user settings. Closing this, @tas50 let me know if I am misunderstanding the concern of this issue
