### ISSUE TITLE
Progress bar is incorrect

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-analyze#136]
## Description
During our last customer demo the progress bar would continually stop at 93% when the analyze process was complete.

## Chef Analyze Version
Chef Workstation 0.13.35 (I don't think we have a `--version` flag for `chef-analyze` yet)

## Platform Version
I believe it was a linux box that was SSHed into from a Windows box

**Comment by marcparadise** [comment]
I'm picking this up as I was already in the process of debugging it from another direction - discovered similar behavior when trying to move progressbar and terminal IO out of the reporting package.

**Comment by robbkidd** [comment]
I could reproduce this with the command `chef analyze report cookbooks`:

```
» chef analyze report cookbooks
Finding available cookbooks... (335 found)
Analyzing cookbooks...
301 / 335 [-----<extra dashes removed>------->______________] 89.85% 195 p/s

-- REPORT SUMMARY --
[... extra output removed ...]
```

The command involving _more_ work `chef analyze report cookbooks --verify-upgrade`, would reliably reach 100%

```
» chef analyze report cookbooks --verify-upgrade
Finding available cookbooks... (335 found)
Analyzing cookbooks...
335 / 335 [-----<extra dashes removed>----------------------] 100.00% 25 p/s

-- REPORT SUMMARY --
[... extra output removed ...]
```
