### ISSUE TITLE
[user/customer] Create cookbook oriented aggregation report

### ISSUE THREAD

**Issue by afiune** [chef/chef-analyze#17]
## Motivation

As a **Chef customer**,
I want a report of all cookbook violations,
so that I can fix them in preparation for upgrading my chef infra client version.

## Specification
Create a report that looks like this that can be persisted:

| Cookbook Name      | Version | Violations | Automatically Correctable | Nodes (...)                         |
|--------------------|---------|------------|--------------|-------------------------------------|
| tacobell_users     | 0.1.0   | 59         | 50           |                                     |
| tacobell_users     | 0.9.10  | 61         | 34           | node2, node10                       |
| tacobell_users     | 0.10.0  | 49         | 31           | node1, node3, node99                |
| tacobell_hardening | 0.1.0   | 27         | 27           |                                     |
| tacobell_hardening | 0.1.1   | 12         | 5            | node4, node5, node88                |
| tacobell_hardening | 1.1.2   | 0          | 0            | node6, node7, node8, node80, node90 |

Create a summary report that looks like this::
```
tacbell_users (0.1.0)
    59 violations, 50 automatically remediable, 0 nodes affected
tacobell_users (0.9.10)
    61 violations, 34 automatically remediable, 2 nodes affected
...
```

## Downstream Impact

None

## Acceptance Criteria
The report is formatted so UX and Product can analyze it. (Human and CSV formats)

**Comment by marcparadise** [comment]
Would recommend on this report that we not include node details, only a count of affected nodes. When you might have tens, hundreds or thousands of nodes in a list, it'll quickly get overwhelming.

**Comment by afiune** [comment]
Closed by https://github.com/chef-analyze/issues/79
