### ISSUE TITLE
Enhance cookbook reports to include Policy file information

### ISSUE THREAD

**Issue by mudash** [chef/chef-analyze#231]
Customers use policyfiles but our current `chef analyze report` implementation does not retrieve any information on them.

# Acceptance Criteria

Update `report cookbooks` to show any policyfile information that is present. The following reports will be updated:

### Cookbooks report summary

Current output:
```
       Cookbook        Version   Violations   Auto-correctable   Nodes Affected
---------------------+---------+------------+------------------+-----------------
  aig-auth             0.2.7              0                  0                7
  aig-auth             0.4.1              0                  0                6
  aig-auth             0.4.4              0                  0              170
```

Desired output:
```
    Cookbook     Version   Policy            Policy Revision   Violations   Auto-correctable   Nodes Affected  
---------------+---------+-------------+-----------------+------------+------------------+-----------------
  aig-auth       0.2.7                                              0                  0                7  
  aig-auth                 Web Server    123456...                  0                  0                6  
  aig-auth                 Web Server    abcdef...                  0                  0              170  
```
Add 2 columns for policy name and revision. The revision will be shortened with ellipses because displaying the entire revision would make the table much wider than most monitors can support in a terminal. If using a policy file, leave the version blank. If not using a policy file, leave policy and policy revision blank.

### Cookbook txt report

Current output:
```
> Cookbook: aig-auth (0.2.7)
  Nodes affected: livvspdstage3, livvspgit01, livvspns01, livvspnwbmstr, livvsprhsat02, livvspsl01, supermarket.aig.net
> Cookbook: aig-auth (0.4.1)
  Nodes affected: livvsdalgo01, livvsdcmcnee02, livvsdcpotturi, livvsdjenkm02, livvsdrevport01, livvsdsrajend02
```

Desired output:
```
> Cookbook: aig-auth (0.2.7)
  Policy Groups: none
  Nodes affected: livvspdstage3, livvspgit01, livvspns01, livvspnwbmstr, livvsprhsat02, livvspsl01, supermarket.aig.net
> Cookbook: aig-auth (policy Web Server Prod, revision 123456)
  Policy Groups: Web Server Prod, Web Server Dev
  Nodes affected: livvsdalgo01, livvsdcmcnee02, livvsdcpotturi, livvsdjenkm02, livvsdrevport01, livvsdsrajend02
```
Replace the version number with the policy name and full revision. Add a line to every cookbook segment displaying the policy groups this policy is attached to, if any.

### Cookbooks csv report

Current output:
```
Cookbook Name,Version,Nodes
aig-auth,0.2.7,livvspdstage3 livvspgit01 livvspns01 livvspnwbmstr livvsprhsat02 livvspsl01 supermarket.aig.net
aig-auth,0.4.1,livvsdalgo01 livvsdcmcnee02 livvsdcpotturi livvsdjenkm02 livvsdrevport01 livvsdsrajend02
```

Desired output:
```
Cookbook Name,Version,Policy,Policy Revision,Policy Groups,Nodes
aig-auth,0.2.7,,,,livvspdstage3 livvspgit01 livvspns01 livvspnwbmstr livvsprhsat02 livvspsl01 supermarket.aig.net
aig-auth,,Web Server,123456,"Web Server Prod, Web Server Dev",livvsdalgo01 livvsdcmcnee02 livvsdcpotturi livvsdjenkm02 livvsdrevport01 livvsdsrajend02
```
Add columns for Policy, Policy Revision, and Policy Groups. For non-policyfile cookbooks those columns are blank. For policyfile cookbooks the version column is blank. Use a comma separated string for the Policy Groups that much be wrapped in quotes for csv to render it correctly.

**Comment by tyler-ball** [comment]
Implementation notes:

We need to retrieve the Cookbooks used by Policy File, at a high level via the following workflow:
 
1. Find the policies and their revisions used by nodes
2. Find the version of cookbooks 
3. Retrieve these cookbook versions via `/Cookbook_artifacts` end point
4. Combine the above results with cookbooks retrieved via `/Cookbook` end point

**Comment by tyler-ball** [comment]
We did some discovery in #236 around how to present information when users are managing policyfiles. We want to setup a meeting with product and the policyfile users to determine the right way to go forward on this.

**Comment by marcparadise** [comment]
Some thoughts from our discussion: 

Generally, we would expect that a single policy revision is active in a group at a time; but there can be some data lag: if a new policy is pushed out, the old policy will still come up in search results until all nodes in the group have converged with the new policy. 

When we remove revision ID from the output (which I think is correct - this is not actionable data in a summary report), it becomes possible to get two or more revisions of a policy in a group. In a report that only shows policy_group+policy+cookbook, we'd have the potential for duplicates. Revision ID keeps it unique currently. 

In any case, adding the policy group will be important - it provides needed context to understanding what you're seeing.

**Comment by tyler-ball** [comment]
What happens when a new policy revision is added to a policy group? Can a single policy group contain the same policy with more than 1 active revision?

Trying to get that question answered

**Comment by tyler-ball** [comment]
First pass: Remove revision ID from the summary report and txt/csv reports. Sort by 1) Policy Group, 2) Policy Name, 3) Cookbook Name, 4) Cookbook Version. This means in a mixed environment (policyfile + non-policyfile) the report would group policyfile cookbooks together and non-policyfile cookbooks together, making the report easier to read.

**Comment by tyler-ball** [comment]
Merged!
