### ISSUE TITLE
Test policy fetching and merging logic

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-analyze#236]
## Specification

https://github.com/chef/chef-analyze/issues/231 is too big and complex so we want to spike on a potential implementation.

## Acceptance Criteria

1. Add cookbook fetching logic for the Policyfile case
1. Merge policyfile managed cookbooks and non-policyfile managed cookbooks so they are ready to be processed by the output formatters

**Comment by mudash** [comment]
Here is a snapshot of running this logic against chef-utility org on hosted Chef Server which is mostly managed by Policies:
![Screen Shot 2020-04-30 at 2.27.27 PM.png](https://images.zenhubusercontent.com/5dadd7956a7fc5000106ebd0/11a08825-d424-4685-b2e6-42335c884c87)

**Comment by tyler-ball** [comment]
Remaining work on this: unit tests. Any further work about changing the report structure will be covered in #231

**Comment by mudash** [comment]
merged https://github.com/chef/go-chef/pull/23
this issue can be closed.
