### ISSUE TITLE
Top level report and capture commands

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-analyze#242]
# Acceptance Criteria

1. Move `chef analyze report` to `chef report`
2. Move `chef analyze capture` to `chef capture`
3. Both these commands should appear under the 'experimental' block in the help text:
```
Usage:
    chef -h/--help
    chef -v/--version
    chef command [arguments...] [options...]

Available Commands:
    exec                    Runs the command in context of the embedded ruby
    env                     Prints environment variables used by Chef Workstation
    ...

Experimental Commands:
    report                    Report on the state of existing infrastructure from a Chef Infra Server
    capture                 Copy the state of an existing node locally for testing and verification
```
4. ~Rename the feature flag from 'analyze' to 'upgrade_labs'~ We're going to remove the feature flag in https://github.com/chef/chef-workstation/issues/1135
    1. ~In the Chef Workstation App the UI should be updated from `chef analyze command` to `Upgrade Lab`. The description can stay the same~
    1. ~In the golang feature flag library, update the feature flag environment variable and config value from 'analyze' to 'upgrade_lab'~
5. There is no longer a `chef analyze` subcommand
6. Update the help text for `chef report` to be:
```
Generate reports from a Chef Infra Server. Can aggregate information by nodes or cookbooks.

Usage:
  chef-analyze report [command]
  ...
```
7. Update the help text for `chef report nodes` to be:
```
Generates a nodes oriented report containing basic information about the node,
any applied policies, and the cookbooks used during the most recent chef-client run.

Usage:
  chef-analyze report nodes [flags]
  ...
```
8. `chef analyze upload` becomes a hidden subcommand under `chef report upload`
9. Update onboarding documentation to change reference new commands

# Questions

* Do we have tab-completion for these `chef` subcommands? If so, we want to remove `chef report upload` from the list so users do not see it.

**Comment by tyler-ball** [comment]
`chef-analyze` can still stay as the executable under the covers, as long as we can remove references to this in the help documentation from `chef report` and `chef capture`

**Comment by jonong1972** [comment]
Looks good to me!

**Comment by marcparadise** [comment]
> "Can aggregate information by nodes or cookbooks." 

I recommend that we don't include that additional text in the short description. It makes the line long/likelier to wrap.  The operator can also see the same information by running `chef report` with no args.

**Comment by marcparadise** [comment]
I'm not sure that `chef report upload` is right - `chef upload` might be better; if it's a subcommand of `report` it implies it will upload reports; but in reality it uploads the thing at the path you give it, with no assumptions around being for reports. 

In other words if I do  this: 
`chef report nodes`
Then 
`chef report upload`

I would expect the behavior to be uploading the report I just generated.  Since we have to tell it where to upload from, the actual usage will be: 
`chef report upload ~/.chef-workstation/reports/1234.csv`; at that point I think it makes more sense to use `chef upload ~/.chef-workstation/reports/1234.csv`

**Comment by marcparadise** [comment]
This has three associated PRs:

* https://github.com/chef/chef-analyze/pull/256 
* https://github.com/chef/go-libs/pull/29
* https://github.com/chef/chef-workstation/pull/1154
