### ISSUE TITLE
support data bags in chef capture

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-analyze#261]
# Motivation 

As a chef customer looking to upgrade my infrastructure,
I want to verify my cookbook compatibility with Chef INfra 16 
Even if the cookbooks reference data bags. 

# Description
The `capture` command does not currently capture data bags referenced in downloaded cookbooks. This leads to operators needing to manually download the data bags required by their cookbooks. Since the intent of capture is to provide an environment as close to the real environment as possible, data bag support is necessary to provide a single command to clone a node.

# Approaches
* As part of capture, run a custom rubocop/chefstyle cop that identifies data bag usage (through `search("data_bag_name")` and `data_bag_item(name)`
* Proxy data bag requests in the guests, and capture the accessed data bags to local storage
* Proxy data bag requests in the guests, and mock an empty return
* Download *all* data bags from the server in `chef capture`

# Questions

* For a given data bag, should we clone the data bag items from the server or create dummy ones full of empty information? It seems like users leverage data bags to operate on real infrastructure so cloning real information could mean their `chef capture` environment changes real infrastructure.
  * Nothing about the data bag API or usage has changed from 12 -> 15. Is adding real data to those folders useful to customers in helping upgrade?
  * There are lots of ways customers can hurt their infrastructure converging a captured node if they do not understand the downstream effects of their cookbooks. Do we want to potentially 'fail' their converge by not cloning their data bag information in an effort to protect them?
* If we create empty data bags, do we also want to mock out their internal schema? If we do not there does not seem to be much value in creating the actual data bags.

# Acceptance Criteria

* When a user runs `chef capture`, if the cookbooks applied to the node leverage data bags, we prompt and ask the user if they would like us to download all data bags.
  * We warn that this could potentially be a large download
  * We warn that encrypted data bags will not be decrypted and could cause client run failures
  * We don't warn that there is no native API to know what data bags a cookbook leverages without introspection.
* We expose a flag `--[no-]data-bags`. If provided, we do not prompt the user.

**Comment by tyler-ball** [comment]
We have a lot of questions around the *best* way to handle this that we cannot answer today. So we are going to add some really dumb functionality (download all data bags if the user accepts that) and get feedback from the field on how to improve this.

**Comment by marcparadise** [comment]
```
to_be_ignored
```
