### ISSUE TITLE
Feature Request: CMDB Functionality 

### ISSUE THREAD

**Issue by kmf** [chef/chef-analyze#7]
I would love the ability to see more info, something similar to [Ansible CMDB](https://github.com/fboender/ansible-cmdb),
visualizing OHAI data.

a bonus would be the ability to export to CSV and HTML

**Comment by tyler-ball** [comment]
Thanks @kmf - we have some other issues here now talking about generating 'user readable' reports (EG, "how many cookbook violations do I have") and 'Chef Software readable reports' that have more data. The idea is that we could use those Chef-oriented reports to feedback into a process that helps us design better, more useful user reports.

The `chef-analyze` tool is primarily geared towards helping users find cookbook violations that will prevent them from upgrading their Chef Infra Client versions. We want to make it as easy and safe as possible for users that have Chef Infra Client 12 installed across their whole fleet to upgrade to Chef Infra Client 15 so they can adopt newer, easier, and better patterns for managing their infrastructure.

I agree that Chef Infra Client collects a lot of great CMDB type information but I _think_ a better place to visualize that would be Chef Automate. But I think there is OHAI information that users may want to use as part of their Chef Infra Client upgrade process (EG, "I want to upgrade Chef on all my Windows nodes").

Issue where we want to generate CSV exports that include OHAI data: https://github.com/chef/chef-analyze/issues/15

Are Chef Infra Client upgrades something you need to perform in your infrastructure?

**Comment by kmf** [comment]
Yes. 

I'll log this as a feature request on the Automate repo.

**Comment by tyler-ball** [comment]
Thanks @kmf! I'm going to close this and link to the existing cards we have about generating reports. Once we have those reports generated and you can use them, if you think there is additional information that should be included we can file that as a feature request.

https://github.com/chef/chef-analyze/issues/15
https://github.com/chef/chef-analyze/issues/16
https://github.com/chef/chef-analyze/issues/17

Or feel free to add comments / requests for specific ohai data you think should be included if you know what fields you would like to see.
