### ISSUE TITLE
Calculate screen size

### ISSUE THREAD

**Issue by afiune** [chef/chef-analyze#83]
### Describe the Enhancement:

When a user runs a command on a small terminal the reports that are displayed will end up
in a very weird format since we are defaulting the screen size to XXX a static number. We
need to either calculate the screen size and display the report on that size or notify the user
so that the screen is to small to run the report.

The recommendation is to have a screen size of **80 characters**.

### Current Alternative

The user needs to expand the screen on their own. They sometimes get confused.

**Comment by tyler-ball** [comment]
UX proposed 80 characters but we don't think that is enough to display a multi-column table. We propose setting the table to 120 characters in width and outputting a warning to users at the end of the output telling them to resize their terminal window to 120 characters or more.

During implementation, if we decide 120 isn't enough we can decide to increase that value, or possibly reduce the amount of data that we display.

**Comment by afiune** [comment]
Closed by https://github.com/chef/chef-analyze/pull/90
