### ISSUE TITLE
Add --only-unused flag to cookbooks report

### ISSUE THREAD

**Issue by afiune** [chef/chef-analyze#84]
### Describe the Enhancement:

Update the default behavior of the reports to only include cookbooks that are assigned to nodes. Remove the `--skip-unused` flag because that becomes the default behavior.

Create an `--only-unused` flag so that users can have a report that displays 
cookbooks that are NOT used by any node. This is the nemesis of the flag
`--skip-unused` that do not include unused cookbooks that are not applied
to any nodes.

### Describe the Need:

As a user, I would benefit from this report to know and understand how many
and, which cookbooks are not being used. Probably, even remove them.

### Current Alternative

Use https://github.com/chef/knife-tidy

**Comment by afiune** [comment]
Could we switch to default the `report cookbooks` command to display only cookbooks
that are being used by one or more node and have a flag called `--with-unused` to include
the unused cookbooks to the report.

**Comment by tyler-ball** [comment]
Discussed during planning and updated card description - going to stick with `--only-unused`.
