### ISSUE TITLE
[Cookbooks Report] Order cookbooks by name

### ISSUE THREAD

**Issue by afiune** [chef/chef-analyze#98]
### Describe the Enhancement:
For the Cookbooks Report, order the displayed cookbook by alphabetical name.

### Describe the Need:
For any operator that uses this report, it would be difficult to digest the list
of cookbooks if they are not ordered in a predictable way.

### Acceptance Criteria

* Cookbooks are displayed in alphabetical order.

### Current Alternative
None. (or probably use `sort` unix command)

**Comment by vsingh-msys** [comment]
Yes, because Chef Infra Server API returns the cookbooks in an unsorted way. I have applied this in order to sort the cookbooks

```
sort.Slice(results, func(i, j int) bool {
		return results[i].Name < results[j].Name
	})
```
